{
  "openapi": "3.0.0",
  "info": {
    "title": "AV_conf API",
    "version": "1.0",
    "description": "API documentation for AV_conference",
    "contact": {
      "name": "Dineshkumar",
      "email": "dineshkumar.b@tra-augment.com",
      "url": "http://www.3edge.in"
    },
    "termsOfService": "https://www.termsofservice.com",
    "license": {
      "name": "MIT",
      "url": "https://github.com/b-dinesh-kumar/AV_conf/"
    }
  },
  "servers": [
    {
      "url": "http://localhost:9090/v1"
    }
  ],
  "paths": {
    "/meeting": {
      "get": {
        "summary": "getAllMeeting",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "meetingId": {
                        "type": "string",
                        "example": "ad45e34er35"
                      },
                      "meetingDesc": {
                        "type": "string",
                        "example": "This meeting is about API documentation"
                      },
                      "isScreenshareUsed": {
                        "type": "boolean"
                      },
                      "schStartTime": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2020-09-22T23:30:52.123Z"
                      },
                      "schEndTime": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2020-09-22T25:30:52.123Z"
                      },
                      "isWaitRoomEnabled": {
                        "type": "boolean"
                      },
                      "actStartTime": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2020-09-22T24:30:52.123Z"
                      },
                      "actEndTime": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2020-09-22T26:30:52.123Z"
                      },
                      "isAudioUsed": {
                        "type": "boolean"
                      },
                      "isVideoUsed": {
                        "type": "boolean"
                      },
                      "isRecordingUsed": {
                        "type": "boolean"
                      },
                      "meetingUrl": {
                        "type": "string",
                        "example": " https://av-meet.com/idc-vshh-vkp"
                      },
                      "meetingStatus": {
                        "type": "string",
                        "example": "Completed"
                      },
                      "meetingName": {
                        "type": "string",
                        "example": "General Meeting"
                      }
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": [
                      {
                        "meetingId": "ad45e34er35",
                        "meetingDesc": "This meeting is about API documentation",
                        "isScreenshareUsed": true,
                        "schStartTime": "2020-09-22T23:30:52.123Z",
                        "schEndTime": "2020-09-22T25:30:52.123Z",
                        "isWaitRoomEnabled": true,
                        "actStartTime": "2020-09-22T24:30:52.123Z",
                        "actEndTime": "2020-09-22T26:30:52.123Z",
                        "isAudioUsed": true,
                        "isVideoUsed": true,
                        "isRecordingUsed": true,
                        "meetingUrl": " https://av-meet.com/idc-vshh-vkp",
                        "meetingStatus": "string",
                        "meetingName": "General Meeting"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "operationId": "get-meeting",
        "description": "Get all the meeting details.",
        "parameters": [
          {
            "schema": {
              "type": "number",
              "example": 1
            },
            "in": "query",
            "name": "page",
            "description": "page_no"
          },
          {
            "schema": {
              "type": "string",
              "example": "2020-09-22T18:30:52.123Z"
            },
            "in": "query",
            "name": "startTime",
            "description": "meeting_strat_time"
          },
          {
            "schema": {
              "type": "string",
              "example": "0"
            },
            "in": "query",
            "name": "orderBy",
            "description": "Order the page by startTime"
          }
        ],
        "security": [
          {
            "API Key - 1": []
          }
        ]
      },
      "parameters": [],
      "post": {
        "summary": "createMeeting",
        "operationId": "post-meeting",
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Meeting created successfully."
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "message": "Meeting created successfully."
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "To create the meeting.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "meetingDesc": {
                    "type": "string",
                    "example": "This is a meeting about API documentation"
                  },
                  "schStartTime": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2020-09-22T23:30:52.123Z"
                  },
                  "schEndTime": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2020-09-22T25:30:52.123Z"
                  },
                  "userId": {
                    "type": "string",
                    "example": "ff34d-dff4r"
                  },
                  "meetingName": {
                    "type": "string",
                    "example": "SprintMeeting"
                  }
                },
                "required": [
                  "meetingDesc",
                  "schStartTime",
                  "schEndTime",
                  "userId",
                  "meetingName"
                ]
              },
              "examples": {
                "example-1": {
                  "value": {
                    "meetingDesc": "This is a meeting about API documentation",
                    "schStartTime": "2020-09-22T23:30:52.123Z",
                    "schEndTime": "2020-09-22T25:30:52.123Z",
                    "userId": "ff34d-dff4r",
                    "meetingName": "SprintMeeting"
                  }
                }
              }
            },
            "application/xml": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          },
          "description": "Details to create the meeting."
        },
        "security": [
          {
            "API Key - 1": []
          }
        ],
        "parameters": []
      }
    },
    "/meeting/{id}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "id",
          "in": "path",
          "required": true,
          "description": "meeting_Id"
        }
      ],
      "get": {
        "summary": "getMeetingById",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "meetingId": {
                      "type": "string",
                      "example": "ad45e34er35"
                    },
                    "meetingDesc": {
                      "type": "string",
                      "example": "This meeting is about API documentation"
                    },
                    "isScreenshareUsed": {
                      "type": "boolean"
                    },
                    "schStartTime": {
                      "type": "string",
                      "example": "2020-09-22T23:30:52.123Z"
                    },
                    "schEndTime": {
                      "type": "string",
                      "example": "2020-09-22T23:30:52.123Z"
                    },
                    "isWaitRoomEnabled": {
                      "type": "boolean"
                    },
                    "actStartTime": {
                      "type": "string",
                      "example": "2020-09-22T24:30:52.123Z"
                    },
                    "actEndTime": {
                      "type": "string",
                      "example": "2020-09-22T26:30:52.123Z"
                    },
                    "isAudioUsed": {
                      "type": "boolean"
                    },
                    "isVideoUsed": {
                      "type": "boolean"
                    },
                    "isRecordingUsed": {
                      "type": "boolean"
                    },
                    "meetingUrl": {
                      "type": "string",
                      "example": "https://av-meet.com/idc-vshh-vkp"
                    },
                    "meetingStatus": {
                      "type": "string",
                      "example": "Completed"
                    },
                    "meetingName": {
                      "type": "string",
                      "example": "General Meeting"
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "meetingId": "ad45e34er35",
                      "meetingDesc": "This meeting is about API documentation",
                      "isScreenshareUsed": true,
                      "schStartTime": "2020-09-22T23:30:52.123Z",
                      "schEndTime": "2020-09-22T23:30:52.123Z",
                      "isWaitRoomEnabled": true,
                      "actStartTime": "2020-09-22T24:30:52.123Z",
                      "actEndTime": "2020-09-22T26:30:52.123Z",
                      "isAudioUsed": true,
                      "isVideoUsed": true,
                      "isRecordingUsed": true,
                      "meetingUrl": "https://av-meet.com/idc-vshh-vkp",
                      "meetingStatus": "ended"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-meeting-id",
        "description": "Get the meeting details by id."
      },
      "delete": {
        "summary": "deleteMeetingById",
        "operationId": "delete-meeting-id",
        "responses": {
          "204": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "messgae": {
                      "type": "string",
                      "example": "Deleted successfully."
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "messgae": "Deleted successfully."
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Delete the meeting by id."
      },
      "patch": {
        "summary": "updateMeetingById",
        "operationId": "patch-meeting-id",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Updated successfully"
                    }
                  }
                }
              }
            }
          }
        },
        "description": "To update the meeting by id.",
        "security": [
          {
            "API Key - 1": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "meetingName": {
                    "type": "string",
                    "example": "FirstMeeting"
                  },
                  "meetingDesc": {
                    "type": "string",
                    "example": "This is a meeting about updation"
                  }
                }
              },
              "examples": {}
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {
      "API Key - 1": {
        "type": "oauth2"
      }
    }
  }
}